In [52]:
#create vectors for my matrix
A<- c(1,2,3)
B<- c(4,5,6)

In [74]:
# testing my vectors
A
B

[1] 1 2 3

[1] 4 5 6

In [75]:
#adding A and B tas a new colum
rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

In [76]:
# Create a 3 x 3 matrix consisting of the numbers 1-9
mat<- matrix(1:9, nrow=3)

In [77]:
# testing matrix
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [78]:
#confirming that is a matrix
class(mat) =='matrix'

[1] TRUE

In [79]:
#Create a 5 x 5 matrix consisting of the numbers 1-25 
mat2 <- matrix(1:25,nrow=5, byrow=TRUE)

In [81]:
# Testing the matrix
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [82]:
# taking out specific numbers from matrix 
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [83]:
# taking out specific numbers from matrix 
mat2[4:5, 4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

In [84]:
# sum of all elements on the matrix 
sum(mat2)

[1] 325

In [63]:
# this is to look for information about built in functions
help(runif)

In [85]:
# Using runif for the first time. It creates random numbers
maybe <- runif(20)

In [86]:
#Testing the random numbers
maybe

[1] 0.272329463 0.452474676 0.212743173 0.063312214 0.815610854 0.480173857
 [7] 0.006104606 0.911309999 0.905980461 0.780405062 0.364782197 0.759066108
[13] 0.856231930 0.446725957 0.041256396 0.582426799 0.164857126 0.860657965
[19] 0.920224232 0.292466890

In [88]:
# assigning random numbers to a matrix of 4 rows and 5 columns
mat3<-matrix(maybe,byrow=TRUE,nrow=4)

In [89]:
mat3

[,1]      [,2]        [,3]      [,4]       [,5]     
[1,] 0.2723295 0.452474676 0.2127432 0.06331221 0.8156109
[2,] 0.4801739 0.006104606 0.9113100 0.90598046 0.7804051
[3,] 0.3647822 0.759066108 0.8562319 0.44672596 0.0412564
[4,] 0.5824268 0.164857126 0.8606580 0.92022423 0.2924669